return table.freeze({
    lumenreach = table.freeze({
        Music = table.freeze({
            AssetId = "rbxassetid://1848017039", -- Morning Breeze Main · APMOfficial
            BaseVolume = 0.28,
        }),
        Ambience = table.freeze({
            AssetId = "rbxassetid://9112781510", -- Forest Ambience 1 (SFX) · ProSoundEffects
            BaseVolume = 0.15,
        }),
    }),
    brasshaven = table.freeze({
        Music = table.freeze({
            AssetId = "rbxassetid://9040092810", -- Grey Shores main · APMOfficial
            BaseVolume = 0.26,
        }),
        Ambience = table.freeze({
            AssetId = "rbxassetid://9112761348", -- Construction Presence 1 (SFX) · ProSoundEffects
            BaseVolume = 0.07,
        }),
    }),
})
